Makefile: never use -linkall without $(COMPFLAGS)
The "threads" package of ocamlfind, which "lwt.unix" depends on, is
set up in such a way that using -linkall without passing ocamlfind one
of the -thread or -vmthread options breaks the build (an alternative
is to pass -predicates mt,mt_posix). $(COMPFLAGS) contains -thread,
so `-linkall $(COMPFLAGS)` works.

This PR fixes the following build error by removing `-linkall` from
the latex2stog binaries (that I don't think need it?):

```
$ ocamlfind ocamlopt -o latex2stog \
  -package ppx_blob,xtmpl,ptime,ocf,ocf.ppx,dynlink,unix,str,higlo.lexers,lwt.unix,xtmpl.ppx,uri,uutf \
 -linkall -linkpkg stog.cmxa latex2stog.cmx
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Thread referenced from /home/gasche/.opam/4.06.1/lib/lwt/lwt_unix.cmxa(Lwt_preemptive)
         Mutex referenced from /home/gasche/.opam/4.06.1/lib/lwt/lwt_unix.cmxa(Lwt_preemptive)
         Condition referenced from /home/gasche/.opam/4.06.1/lib/lwt/lwt_unix.cmxa(Lwt_preemptive)
```